[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True
allow_redefinition = True
disable_error_code = no-redef

# Be a bit more permissive
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = False
no_implicit_optional = False
strict_optional = False
warn_no_return = True
warn_redundant_casts = True
warn_unused_ignores = True

# Imports
ignore_missing_imports = True

# Platform specific
# mypy_path =
# plugins =
